name: app_lock
description: Flutter App Lock Screen
version: 0.1.0
homepage: https://github.com/inulugbek/app_lock
issue_tracker: https://github.com/inulugbek/app_lock/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  local_auth: ^1.1.4
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.3.1
  coverage: ^1.0.2
